base_url = "https://louis.feuvrier.org"
title = "Louis Feuvrier's ::1"
compile_sass = true
build_search_index = true
theme = "hallo"

[markdown]
highlight_code = true


[extra.theme]
background = "#002b36"
foreground = "#657b83"
hover = "#586e75"

[extra.author]
name = "Louis"
[extra]
greeting = "Bonjour!"
iam = "My name is"
links = [
  { title = "github", url = "https://github.com/mqnfred", icon = "github", color = "#dc322f" },
  { title = "resume", url = "https://louis.feuvrier.org/louis_feuvrier-resume.pdf", iconset = "fas", icon = "file-pdf", color = "#859900" },
  { title = "linkedin", url = "https://www.linkedin.com/in/louis-feuvrier-258a0861/", icon = "linkedin", color = "#268bd2" },
  { title = "email", url = "mailto:louis@feuvrier.org", iconset = "fas", icon = "envelope", color = "#b58900" }
]
